In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import math
import numpy as np
from numpy import random as npr

dtRNN = 0.002
tauRNN = 0.1
number_units = 300
g = 1.5

class Model(nn.Module):
  def __init__(self, number_units):
    super().__init__()
    self.number_units = number_units

    # g<1 -> damped and g>1 -> chaotic
    self.J = nn.Parameter(g * torch.Tensor(npr.randn(number_units, number_units) / 
                                           math.sqrt(number_units)), requires_grad=True) 
    self.J = nn.Parameter(torch.normal(torch.zeros_like(self.J), torch.ones_like(self.J)*2), requires_grad=True)

  def forward(self,
              activity_data,
              white_noise
              ):
    
    output = torch.tanh(activity_data)
    JR_temp = (torch.matmul(self.J, output).reshape((self.number_units, 1)) + white_noise) 
    new_hidden_state = activity_data + dtRNN*(-activity_data + JR_temp)/tauRNN 
 
    return output, new_hidden_state
    

rnn_model = Model(number_units)
    

In [2]:
rnn_model.load_state_dict(torch.load("ok_weights.pt"))

<All keys matched successfully>

In [3]:
weight_matrix = rnn_model.J.detach().clone().numpy()

In [4]:
weight_matrix

array([[-9.8748541e+00, -5.9738614e-02,  8.8842249e-01, ...,
         3.1120980e-01, -2.3924680e-03,  5.6192821e-01],
       [-2.8872690e-01, -2.9271207e+00,  4.8316413e-01, ...,
         4.9839857e-01,  1.0274951e+00,  2.2851178e-01],
       [-3.6024085e-01, -5.8363152e-01, -1.5323781e+01, ...,
         1.2617437e+00, -2.7201694e-01, -9.9397302e-01],
       ...,
       [-7.7181399e-02, -5.1913279e-01, -1.4171814e+00, ...,
        -1.0784763e+01, -6.4301401e-01, -4.2637390e-01],
       [ 3.3906111e-01, -2.5509769e-01,  1.3932756e+00, ...,
        -5.7904096e-04, -8.0503759e+00,  1.8306507e-01],
       [-5.2740842e-01, -1.4329021e-01, -1.4286491e+00, ...,
         1.2569907e+00,  1.5301469e-01, -9.7243862e+00]], dtype=float32)

In [5]:
eigvals, eigvecs = np.linalg.eig(weight_matrix)

In [6]:
eigvecs.shape

(300, 300)

In [7]:
import os
os.environ['PYTHONPATH']

'C:\\Users\\Andrew\\Documents\\PYLIBs\\rnn-fxpts-master'

In [1]:
import rnn_fxpts

In [15]:
import numpy as np
N = np.random.randint(128) # arbitrary number of neurons (within reason)
W = np.random.randn(N,N) # arbitrary connection weight matrix
v = np.random.randn(N,1) # arbitrary neural state
v_new = np.tanh(W.dot(v)) # activation rule

In [1]:
import rnn_fxpts as rfx
N = 2
W = 1.25*np.eye(N) + 0.1*np.random.randn(N,N)


fxpts, _ = rfx.run_solver(W)
fxpts

ModuleNotFoundError: No module named 'rnn_fxpts'

In [18]:
W

array([[ 1.09896686, -0.08630417],
       [-0.03337969,  1.29426132]])

In [2]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import math
import numpy as np
from numpy import random as npr

dtRNN = 0.002
tauRNN = 0.1
number_units = 300
g = 1.5

class Model(nn.Module):
  def __init__(self, number_units):
    super().__init__()
    self.number_units = number_units

    # g<1 -> damped and g>1 -> chaotic
    self.J = nn.Parameter(g * torch.Tensor(npr.randn(number_units, number_units) / 
                                           math.sqrt(number_units)), requires_grad=True) 
    self.J = nn.Parameter(torch.normal(torch.zeros_like(self.J), torch.ones_like(self.J)*2), requires_grad=True)

  def forward(self,
              activity_data,
              white_noise
              ):
    
    output = torch.tanh(activity_data)
    JR_temp = (torch.matmul(self.J, output).reshape((self.number_units, 1)) + white_noise) 
    new_hidden_state = activity_data + dtRNN*(-activity_data + JR_temp)/tauRNN 
 
    return output, new_hidden_state
    

rnn_model = Model(number_units)
    

c:\Users\Andrew\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
import rnn_fxpts as rfx

W = np.random.rand(5,5)

fxpts, _ = rfx.run_solver(W)
fxpts



array([[-0.        ,  0.9769771 , -0.9769771 ],
       [-0.        ,  0.91001482, -0.91001482],
       [-0.        ,  0.99813984, -0.99813984],
       [-0.        ,  0.97064138, -0.97064138],
       [-0.        ,  0.99302302, -0.99302302]])

In [21]:
(W @ fxpts).T[1]

array([2.22641736, 1.52761067, 3.48965511, 2.10326412, 2.8273956 ])

array([[-0.        , -0.        , -0.        , -0.        , -0.        ],
       [ 0.9769771 ,  0.91001482,  0.99813984,  0.97064138,  0.99302302],
       [-0.9769771 , -0.91001482, -0.99813984, -0.97064138, -0.99302302]])

In [ ]:
(10,10): 3.7
(20,20): 1 min
